services:
  app:
    build: .
    container_name: actullm_azure_app
    ports:
      - "8081:80"
    env_file:
      - ./src/app2/.env
    environment:
      - LLM_PROVIDER=azure
      - AUTO_VECTORIZE=0
      - CHROMA_PATH=/chroma_data
    volumes:
      - ./chroma_data:/chroma_data
      - ~/.cache/huggingface:/root/.cache/huggingface